version: "3.4"

services:

   flask:
     build: .
     container_name: flask
     volumes:
         - ./:/app
     tty: true
     ports:
         - "5000:5000"
     env_file:
         - ./.env
     command: "gunicorn --bind 0.0.0.0:5000 --reload wsgi:app"
