version: "3.4"

services:

   flask:
     build: .
     container_name: flask
     user: "1000:1000"
     volumes:
         - ./:/app
     tty: true
     ports:
         - "8080:8080"
     env_file:
         - ./.env